name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: mstachniuk/ci-skip@v1
      
      # Runs a set of commands using the runners shell
      - name: Build
        if: ${{ env.CI_SKIP == 'false' }}
        run: |
          echo "This step should not be executed when commit message contains [ci skip]"        
          sudo apt-get update 
          sudo apt-get install -y apt-utils \
          build-essential \
          cmake \
          libgtest-dev \
          libtbb-dev \
          libboost-all-dev \
          liblapack-dev \
          wget \
          unzip
          export TBB_HOME=/usr/lib/x86_64-linux-gnu
          export BOOST_HOME=/usr/lib/x86_64-linux-gnu
          cd
          wget https://github.com/simbody/simbody/archive/Simbody-3.7.tar.gz
          tar xvzf Simbody-3.7.tar.gz
          mkdir $HOME/simbody-build && mkdir $HOME/simbody
          ls
          cd $HOME/simbody-build
          cmake $HOME/simbody-Simbody-3.7 -DCMAKE_INSTALL_PREFIX=$HOME/simbody -DBUILD_VISUALIZER=off
          make -j$(nproc)
          make install
          export SIMBODY_HOME=$HOME/simbody
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make -j$(nproc)
          cd /home/runner/work/SPHinXsys/SPHinXsys
          git submodule update --init
          mkdir build
          cd build 
          cmake ..
          make -j$(nproc)

      - name: Test with the first try
        id: first-try
        if: ${{ env.CI_SKIP == 'false' }}
        run: |
          cd /home/runner/work/SPHinXsys/SPHinXsys
          cd build 
          ctest  --output-on-failure
        continue-on-error: true

      - name: Test with the second try for failed cases
        id: second-try
        if: ${{ env.CI_SKIP == 'false' && steps.first-try.outcome == 'failure' }} 
        run: |
          cd /home/runner/work/SPHinXsys/SPHinXsys
          cd build 
          ctest --rerun-failed --output-on-failure
        continue-on-error: true

      - name: Test with the third try for failed cases
        id: third-try
        if: ${{ env.CI_SKIP == 'false' && steps.second-try.outcome == 'failure' }} 
        run: |
          cd /home/runner/work/SPHinXsys/SPHinXsys
          cd build 
          ctest --rerun-failed --output-on-failure
        continue-on-error: true

      - name: Test with the fourth try for failed cases
        id: fourth-try
        if: ${{ env.CI_SKIP == 'false' && steps.third-try.outcome == 'failure' }} 
        run: |
          cd /home/runner/work/SPHinXsys/SPHinXsys
          cd build 
          ctest --rerun-failed --output-on-failure
        continue-on-error: true

      - name: Test with the last try for failed cases
        if: ${{ env.CI_SKIP == 'false' && steps.fourth-try.outcome == 'failure' }} 
        run: |
          cd /home/runner/work/SPHinXsys/SPHinXsys
          cd build 
          ctest --rerun-failed --output-on-failure

